package source;

public enum DamageType {
	SMITE,ZEALOUSACCUSATION,STUNNINGBLOW,HOLYLANCE,WICKEDSLICE,PISTOLSHOT,POINTBLANKSHOT,GRAPESHOTBLAST,TRACKINGSHOT,DUELISTSADVANCE,OPENVEIN,MACEBASH,JUDGEMENT,DAZZLINGLIGHT,ILLUMINATION,HANDOFLIGHT
}
